### PR TITLE
feat: add Windows OS detection

### LINKED ISSUE #3: Add support for detecting Windows
Currently supported operating systems:

| Executor/OS    | Supported? | Shell |
|---             |---         |---    |
| Docker/Ubuntu  | yes        | Bash  |
| Docker/Debian  | yes        | Bash  |
| Docker/Alpine  | yes        | Bash  |
| macOS          | yes        | Bash  |
| machine/Ubuntu | yes        | Bash  |

CircleCI has since announced support for Windows: https://circleci.com/build-environments/windows/.

Add the ability to detect and set env var data for Windows machines.

### PR DESCRIPTION
**Pull request by distributedlock**
Resolves #3 .

### CODE REVIEW

**Comment by FelicianoTech** [comment]
Hi @RanadeepPolavarapu. Thank you for your PR. I have a couple of questions.

1. Have you tested this PR on your own local orb yet?

2. Can you fix up the commits in this PR? If you look at the "Files Changed" you'll see that there's a lot of changes in this PR that you didn't actually do (I believe). This is likely because you merged master into this PR rather than rebasing this PR on master, which is cleaner.

**Comment by amdprophet** [comment]
@RanadeepPolavarapu I'd love to see your work get merged. Are you still working on this? If not, I may take a stab at implementing this feature.

**Comment by distributedlock** [comment]
Please feel free to take it.

**Comment by gmemstr** [comment]
@amdprophet Hi, have you taken this on? I'll go ahead and mark this as closed for now if so.

**Comment by amdprophet** [comment]
@gmemstr yeah - feel free to close this. I'm aiming to open a PR this week.

**Pull request closed without merging**
